apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-api-secrets
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rag-api-secrets
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: rag-api-secrets-prod
      property: OPENAI_API_KEY
  - secretKey: BEDROCK_GUARDRAIL_ID
    remoteRef:
      key: rag-api-secrets-prod
      property: BEDROCK_GUARDRAIL_ID
