apiVersion: v1
kind: PersistentVolume
metadata:
  name: chroma-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: "vol-04cfdee3709c4d6ff" # Updated from Terraform output
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - ap-southeast-2a # Matches Terraform AZ
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: chroma-pv
  storageClassName: "" # Empty to use the static PV
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vectordb
spec:
  serviceName: "vectordb"
  replicas: 1
  selector:
    matchLabels:
      app: vectordb
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
      - name: chroma
        image: chromadb/chroma:0.5.3
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: chroma-persistence
          mountPath: /chroma/chroma
      volumes:
      - name: chroma-persistence
        persistentVolumeClaim:
          claimName: chroma-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb-service
spec:
  selector:
    app: vectordb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000